### PR TITLE
Fix actions 

### PR DESCRIPTION
**Pull request by akatumalla-ouster**
## Summary 
- Pin mypy and flake8 versions. 
- [TODO ] Temporary `continue_on_error` on mypy issues to not spend more time, tried:  
1. ubuntu-22.04 has mypy issues with same version of mypy and flake8 that passes on internal builds. 
2. ubuntu-20.04 runner is not supported and 
3. tried to use image built with Dockerfile in `python/` directory but was running to errors. 
Will address the issues in a followup.
- Add header `cstdint` for `ouster_viz/src/screenshot_utils.h` to enable successful builds on 24.04.
- Moved sdk installation to a common file to be reused.
- Updated random_shuffle usage as mac 14 enforces removal of `random_shuffle` in c++ 17 
(even though CMAKE_CXX_STANDARD is set to 14 in CMakelists.txt).

## Validation
CI

### CODE REVIEW

**Review by twslankard — APPROVED** [review]
Lgtm

File: .github/workflows/build_test.yaml [hunk 1]
```diff
@@ -132,7 +139,7 @@ jobs:
     - name: install deps
       run: brew install cmake pkg-config eigen curl libtins glfw flatbuffers googletest ceres-solver robin-map
     - name: cmake configure
-      run: cmake . -B build -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
+      run: cmake . -B build -DCMAKE_CXX_STANDARD=14 -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON
```
[the remark this answers is not in the document]
Comment (akatumalla-ouster) [reply .github/workflows/build_test.yaml:142]: Our cmakelist is correct, we can remove this, I added this to verify the error on mac x86 reg

/Users/runner/work/ouster-sdk/ouster-sdk/tests/lidar_scan_test.cpp:283:14: error: no member named 'random_shuffle' in namespace 'std'
std::random_shuffle(test_array1.begin(), test_array1.end());
~~~~~^

**Review by matthew-lidar — APPROVED** [review]
Looks good! Thanks!
